export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SAVE_PATTERN_START = "SAVE_PATTERNS_START";
export const SAVE_PATTERN_SUCCESS = "SAVE_PATTERNS_SUCCESS";
export const SAVE_PATTERN_FAIL = "SAVE_PATTERNS_FAIL";

export const FETCH_PATTERNS_START = "FETCH_PATTERNS_START";
export const FETCH_PATTERNS_SUCCESS = "FETCH_PATTERNS_SUCCESS";
export const FETCH_PATTERNS_FAIL = "FETCH_PATTERNS_FAIL";

export const SET_LOCK_MODE = "SET-LOCK-MODE";
export const UPDATE_ACTIVE_COLOR_SELECTION = "UPDATE-ACTIVE-COLOR-SELECTION";
export const SET_ACTIVE_PATTERN = "SET-ACTIVE-PATTERN";

export const INIT_PATTERN = "INIT_PATTERN";
export const SWITCH_TILE = "SWITCH-TILE";
export const LOCK_TILE = "LOCK-TILE";
export const CLEAR_LOCKED_TILES = "CLEAR-LOCKED-TILES";
export const RANDOMISE_PATTERN = "RANDOMISE_PATTERN";
// Need to do below...
export const UPDATE_IMAGE_NAME = "UPDATE-IMAGE-NAME";
export const UPDATE_COLOR = "UPDATE-COLOR";
export const UPDATE_COMPLEXITY = "UPDATE-COMPLEXITY";
export const UPDATE_ORIENTATION = "UPDATE-ORIENTATION";
export const NEW_TEMPLATE = "NEW-TEMPLATE";
export const LOAD_PATTERN = "LOAD-PATTERN";
export const SAVED_PATTERN = "SAVED-PATTERN";
