export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SAVE_PATTERN_START = "SAVE_PATTERNS_START";
export const SAVE_PATTERN_SUCCESS = "SAVE_PATTERNS_SUCCESS";
export const SAVE_PATTERN_FAIL = "SAVE_PATTERNS_FAIL";

export const FETCH_PATTERNS_START = "FETCH_PATTERNS_START";
export const FETCH_PATTERNS_SUCCESS = "FETCH_PATTERNS_SUCCESS";
export const FETCH_PATTERNS_FAIL = "FETCH_PATTERNS_FAIL";

// "SWITCH-TILE"
// "LOCK-TILE"
// "UPDATE-COMPLEXITY"
// "UPDATE-ORIENTATION"
// "SET-LOCK-MODE"
// "SET-ACTIVE-PATTERN"
// "CLEAR-LOCKED-TILES"
// "NEW-TEMPLATE"
// "UPDATE-COLOR"
// "UPDATE-ACTIVE-COLOR-SELECTION"
// "UPDATE-IMAGE-NAME"
// "LOAD-PATTERN"
// "SAVED-PATTERN"
