export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SAVE_PATTERN_START = "SAVE_PATTERNS_START";
export const SAVE_PATTERN_SUCCESS = "SAVE_PATTERNS_SUCCESS";
export const SAVE_PATTERN_FAIL = "SAVE_PATTERNS_FAIL";

export const FETCH_PATTERNS_START = "FETCH_PATTERNS_START";
export const FETCH_PATTERNS_SUCCESS = "FETCH_PATTERNS_SUCCESS";
export const FETCH_PATTERNS_FAIL = "FETCH_PATTERNS_FAIL";

export const SET_LOCK_MODE = "SET_LOCK_MODE";
export const UPDATE_ACTIVE_COLOR_SELECTION = "UPDATE_ACTIVE_COLOR_SELECTION";
export const SET_ACTIVE_PATTERN = "SET_ACTIVE_PATTERN";

export const INIT_PATTERN = "INIT_PATTERN";
export const SWITCH_TILE = "SWITCH_TILE";
export const LOCK_TILE = "LOCK_TILE";
export const CLEAR_LOCKED_TILES = "CLEAR_LOCKED_TILES";
export const RANDOMISE_PATTERN = "RANDOMISE_PATTERN";
export const UPDATE_BACKGROUND_COLOR = "UPDATE_BACKGROUND_COLOR";
export const UPDATE_PATTERN_COLOR = "UPDATE_PATTERN_COLOR";
export const UPDATE_IMAGE_NAME = "UPDATE_IMAGE_NAME";
export const UPDATE_COMPLEXITY = "UPDATE_COMPLEXITY";
export const UPDATE_ORIENTATION = "UPDATE_ORIENTATION";
export const NEW_TEMPLATE = "NEW_TEMPLATE";
export const SAVED_PATTERN = "SAVED_PATTERN";

// Need to do below...

export const LOAD_PATTERN = "LOAD_PATTERN";
export const DELETE_PATTERN = "DELETE_PATTERN";
